# Generated by Django 5.0.4 on 2024-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_pin_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pin_code",
            field=models.CharField(max_length=10),
        ),
    ]
